# Generated by Django 6.0.1 on 2026-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dish', models.CharField(choices=[('thali', 'Homemade Thali'), ('momo', 'Steamed Momo Platter'), ('biryani', 'Veg Biryani'), ('soup', 'Comfort Veg Soup')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.CharField(max_length=50)),
                ('delivery_time', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
