# Generated by Django 6.0.1 on 2026-02-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
