# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fooditem_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category_custom',
            field=models.CharField(blank=True, default='', help_text='When category is Other, your own category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('rice', 'Rice'), ('veg', 'Veg'), ('non_veg', 'Non-veg'), ('sweets_mithai', 'Sweets (Mithai)'), ('breads', 'Breads'), ('sweets_desserts', 'Sweets & Desserts'), ('pickles_sides', 'Pickles & Side Dishes'), ('curries', 'Curries'), ('soups', 'Soups'), ('snacks', 'Snacks'), ('nepali', 'Nepali'), ('indian', 'Indian'), ('other', 'Other (add your own)')], default='other', max_length=30),
        ),
    ]
